### board create
POST localhost:8080/api/boards
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Cookie: access_token={{accessToken}};

{
  "title": "title",
  "description": "description"
}

> {%
    client.global.set("board_id", response.body.id)
%}

### board column create
POST localhost:8080/api/boards/{{board_id}}/columns
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Cookie: access_token={{accessToken}};

{
  "statusName": "backlog",
  "order": 1
}

> {%
    client.global.set("column_id", response.body.id)
%}

### get board with columns
GET localhost:8080/api/boards/{{board_id}}/columns
Authorization: Bearer {{accessToken}}
Cookie: access_token={{accessToken}};

### get board with columns and cards
GET localhost:8080/api/boards/{{board_id}}/columns
Authorization: Bearer {{accessToken}}
Cookie: access_token={{accessToken}};


### update column
PUT localhost:8080/api/boards/{{board_id}}/columns/{{column_id}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Cookie: access_token={{accessToken}};

{
  "order": 100
}