### create
POST localhost:8080/api/boards
Content-Type: application/json
Authorization: {{accessToken}}

{
  "title": "title",
  "description": "description"
}

> {%
client.global.set("board_id", response.body.id)
%}

### get
GET localhost:8080/api/boards/{{board_id}}
Authorization: {{accessToken}}

### update
PUT localhost:8080/api/boards/{{board_id}}
Content-Type: application/json

{
  "title": "updated title",
  "description": "updated desc"
}


### delete
DELETE localhost:8080/api/board/{{board_id}}



