### 회원가입1
# @no-cookie-jar
POST localhost:8080/api/users/signup
Content-Type: application/json

{
  "username": "helloworld",
  "password": "password"
}

> {%
    client.global.set("user_id1", response.body.result.id)
%}


### 회원가입2
# @no-cookie-jar
POST localhost:8080/api/users/signup
Content-Type: application/json

{
  "username": "foobar",
  "password": "password"
}

> {%
    client.global.set("user_id2", response.body.result.id)
%}


### 로그인
# @no-cookie-jar
POST localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "helloworld",
  "password": "password"
}

> {%
    client.global.set("accessToken", response.body.result.accessToken)
%}

### 보드 생성
POST localhost:8080/api/boards
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Cookie: access_token={{accessToken}};

{
  "title": "title",
  "description": "description"
}

> {%
    client.global.set("board_id", response.body.result.id)
%}

### 컬럼 생성(backlog)
POST localhost:8080/api/boards/{{board_id}}/columns
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Cookie: access_token={{accessToken}};

{
  "statusName": "backlog",
  "order": 1
}

> {%
    client.global.set("column_id1", response.body.result.id)
%}

### 컬럼 생성(ing)
POST localhost:8080/api/boards/{{board_id}}/columns
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Cookie: access_token={{accessToken}};

{
  "statusName": "ing",
  "order": 2
}

> {%
    client.global.set("column_id2", response.body.result.id)
%}

### 컬럼 생성(done)
POST localhost:8080/api/boards/{{board_id}}/columns
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Cookie: access_token={{accessToken}};

{
  "statusName": "done",
  "order": 3
}

> {%
    client.global.set("column_id3", response.body.result.id)
%}


### 보드 조회 (칼럼 & 카드 같이 조회)
GET localhost:8080/api/boards/{{board_id}}/columns
Authorization: Bearer {{accessToken}}
Cookie: access_token={{accessToken}};

### 칼럼 수정
PUT localhost:8080/api/boards/{{board_id}}/columns/{{column_id1}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Cookie: access_token={{accessToken}};

{
  "order": 100
}

### 칼럼 조회
GET localhost:8080/api/boards/{{board_id}}/columns
Authorization: Bearer {{accessToken}}
Cookie: access_token={{accessToken}};

### 파트너 추가
POST localhost:8080/api/boards/{{board_id}}/partners
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Cookie: access_token={{accessToken}};

{
  "userId": {{user_id2}}
}

> {%
    client.global.set("user_id2", response.body.id);
%}

### 카드 추가

### 카드 컬럼 변경

### 카드 댓글 추가

### 카드 삭제

